services:
  web:
    build:
      context: .
      target: prod
    ports:
      - "8080:80"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-strapi}
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  strapi:
    image: strapi/strapi:latest
    platform: linux/arm64/v8
    env_file:
      - .env.strapi
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      DATABASE_SSL: "false"
    volumes:
      - ./strapi:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: