services:
  web:
    build:
      context: .
      target: prod
      args:
        BASIC_AUTH_USER: ${ADMIN_BASIC_USER:-admin}
        BASIC_AUTH_PASS: ${ADMIN_BASIC_PASS:-admin}
    ports:
      - "8080:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - appnet

  api:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://db:27017/mugshop
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_DATABASE=mugshop
    volumes:
      - db_data:/data/db
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  appnet:
    driver: bridge

volumes:
  db_data:
  uploads: